require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe 'Articles', type: :system do
  before do
    driven_by(:rack_test)
  end

  context '#Failed Article Creation' do
    it "Doesn't Create Article Due To Missing Sign In" do
      visit '/articles/new'
      expect(page).to have_text('You need to sign in or sign up before continuing.')
    end
  end

  context '#Succesful Article Creation' do
    it 'Creates An Article After User Sign Up, Sign In, & Category Creation' do
      visit '/auth/sign_up'
    end
  end
end

# before do sign up, sign in and THEN you can create the context create Article
